target-version = "py38"
line-length = 88

[lint]
select = [
    "B", # flake8-bugbear
    "E", # pycodestyle errors
    "F", # Pyflakes
    "W", # pycodestyle warnings
]
ignore = [
    "E501", # ignore line length; auto-formatting will take care of what it can.
]
exclude = [
    "examples/**/*.ipynb",
]

[lint.extend-per-file-ignores]
"cotainr/tests/**/test_*.py" = [
    # The non-standard way to import py.test fixtures in
    # tests means we will need to ignore "imported but not used"
    # as well as argument shadowing tests in test modules.
    "F401",
    "F811",
]
"cotainr/tests/**.py" = [
    "S101", # assertions are OK in tests
]

[lint.pydocstyle]
convention = "numpy"

[format]
exclude = [
    "examples/**/*.ipynb",
]
