FROM fedora:latest
LABEL authors="tor, julius"

ENTRYPOINT ["top", "-b"]


ENV DEBIAN_FRONTEND=noninteractive
RUN set -eux ; \
    dnf upgrade --refresh -y; \
    dnf install -y uv epel-release;\

#install uv
#ADD https://astral.sh/uv/install.sh /uv-installer.sh
#RUN set -eux ;sh /uv-installer.sh && rm /uv-installer.sh
#ENV PATH="/root/.local/bin/:$PATH"

ARG PYTHON_VERSION
ENV PYTHON_VERSION=${PYTHON_VERSION}

#setup environment and install hatchling
RUN set -eux ; \
    uv venv test_environment --python $PYTHON_VERSION;\
    . test_environment/bin/activate;\
    uv pip install hatchling

ARG SINGULARITY_PROVIDER
ENV SINGULARITY_PROVIDER=${SINGULARITY_PROVIDER}

ARG SINGULARITY_VERSION
ENV SINGULARITY_VERSION=${SINGULARITY_VERSION}

RUN echo $SINGULARITY_PROVIDER
RUN echo $SINGULARITY_VERSION

RUN set -eux ; \
#    if [ "$SINGULARITY_PROVIDER" = "apptainer" ]; then \
    dnf install -y $SINGULARITY_PROVIDER-$SINGULARITY_VERSION;\
    singularity --version

#    fi; \
#    if [ "$SINGULARITY_PROVIDER" = "singularity" ]; then \
#        apt -y install singularity-$SINGULARITY_VERSION ;\
#    fi;\
