name: CI on push to branch
on:
#  schedule:
  #    - cron: '17 15 * * *'
  #  workflow_dispatch:
  push:
    branches:
      - docker_dev_env



jobs:
  lint-and-format:
    name: Lint and check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - uses: pre-commit/action@v3.0.1
  run-unittests:
    name: Run unittests
    permissions:
      packages: read
    env:
      # Use docker.io for Docker Hub if empty
      REGISTRY: ghcr.io
      # github.repository as <account>/<repo>
      IMAGE_NAME: ${{ github.repository }}
    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-latest" ]
        python-version: [ "3.9", "3.10" ]#, "3.11", "3.12"]
        singularity: [
          { provider: "singularity", version: "3.8.7" },
          #        {provider: "apptainer", version: "1.1.3"},
          { provider: "apptainer", version: "1.3.4" },
          #        {provider: "singularity-ce", version: "3.9.2"},
          #        {provider: "singularity-ce", version: "4.1.3"},
          #        {provider: "singularity-ce", version: "4.2.1"}
        ]
    container:
      image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/${{ matrix.singularity.provider }}/${{ matrix.singularity.version }}/${{ matrix.python-version }}:docker_dev_env
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Activate uv, install dependencies and run tests
        run: | 
          . /test_environment/bin/activate
          python3 --version
          which python3
          uv pip install -e .[tests]
          pip list
          pytest -vv -m "not endtoend and not singularity_integration and not conda_integration"
