name: Determine CI workflow on push to branch
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"

jobs:
  changed_files:
    runs-on: ubuntu-latest  # windows-latest || macos-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v4

      # determine if docker build files changes
      - name: Get changed files
        id: changed-files-docker-build
        uses: tj-actions/changed-files@823fcebdb31bb35fdf2229d9f769b400309430d0 # v46
        with:
          # Avoid using single or double quotes for multiline patterns
          files: |
            container:
                - '.github/workflows/matrix.json'
                - 'dockerfiles/Dockerfile'
                - '.github/workflows/SCHED_build_docker.yml'
      # Run if files changed
      - name: Run if file(s) changed
        if: steps.changed-files-docker-build.outputs.container_any_changed == 'true'
        run: |
          echo "files changed"
#        uses: peter-evans/repository-dispatch@v3
#        with:
#          token: ${{ secrets.GITHUB_TOKEN }}
#          repository: username/my-repo
#          event-type: rebuild
#          client-payload:





      # Run if files did NOT change
      - name: Run if no file(s) changed
#        uses: peter-evans/repository-dispatch@v3
        if: steps.changed-files-docker-build.outputs.container_any_changed == 'false'
        run: |
          echo "files didnt change"
#        with:
#          token: ${{ secrets.GITHUB_TOKEN }}
#          repository: username/my-repo
#          event-type: test_push
#          client-payload:

