name: CI on push to branch
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  lint-and-format:
    name: Lint and check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - uses: pre-commit/action@v3.0.1

  read_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout to repository
        uses: actions/checkout@v4
      - name: Set matrix data
        id: set-matrix
        run: echo "matrix=$(jq -c . < .github/workflows/matrix_AMD64_limited.json)" >> $GITHUB_OUTPUT

  run-unittests:
    needs: [ read_matrix ]
    name: Run unittests
    permissions:
      packages: read
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.read_matrix.outputs.matrix) }}
    container:
      image: ghcr.io/deic-hpc/cotainr/${{ matrix.singularity.provider }}/${{ matrix.singularity.version }}/${{ matrix.python-version }}:docker_dev_env
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Activate uv, install dependencies and run tests
        run: |
          . /test_environment/bin/activate
          python3 --version
          which python3
          uv pip install -e .[tests]
          pip list
          pytest -vv -m "not endtoend and not singularity_integration and not conda_integration"
