name: CI for release

on:
  workflow_run:
    workflows: ["CI on pull request"]
    branches: [main]
    types: 
      - completed

jobs:
  publish-to-testpypi:
    name: Publish to TestPyPI
    # only publish to TestPyPI on tag pushes and successful test workflow
    if: startsWith(github.ref, 'refs/tags/') && github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest

    environment:
      name: testpypi
      url: https://test.pypi.org/p/cotainr

    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
    - uses: actions/checkout@v4  # Checkout because `uv publish` requires pyproject.toml
    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        name: dist
        path: dist
    - name: Set up uv
      uses: astral-sh/setup-uv@v5
    - name: Publish distribution to TestPyPI
      run: uv publish --index testpypi

    - name: Test TestPyPI build
      run: |
        uv pip install cotainr --index testpypi 
        uv pip install 'cotainr[tests]' # Get Pytest from real PyPI distribution
        pytest .

  publish-to-pypi:
    needs: publish-to-testpypi
    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/p/cotainr

    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
    - uses: actions/checkout@v4  # Checkout because `uv publish` requires pyproject.toml
    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        name: dist
        path: dist
    - name: Set up uv
      uses: astral-sh/setup-uv@v5
    - name: Publish distribution to PyPI
      run: uv publish --index pypi

    - name: Test PyPI build
      run: |
        uv pip install cotainr[tests] --index pypi 
        pytest .
  
