name: CI for release

on:
  workflow_dispatch:
  workflow_run:
    workflows: [CI on pull request]
    branches: [release-gh-action]
    types:
      - completed
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"

jobs:
  build:
    name: Build package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - run: uv build .
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  publish-to-testpypi:
    needs: build
    name: Publish to TestPyPI
    # only publish to TestPyPI on tag pushes and successful test workflow
    # if: github.event.workflow_run.conclusion == 'success'
    # && startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    environment:
      name: testpypi
      url: https://test.pypi.org/p/cotainr

    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
    - uses: actions/checkout@v4  # Checkout because `uv publish` requires pyproject.toml
    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        name: dist
        path: dist
    - name: Set up uv
      uses: astral-sh/setup-uv@v5
    - name: Publish distribution to TestPyPI
      run: uv publish --index testpypi

    - name: Test TestPyPI build
      run: |
        uv venv
	source .venv/bin/activate
        uv pip install cotainr --index testpypi
        uv pip install 'cotainr[tests]' # Get Pytest from real PyPI distribution
        pytest .

  publish-to-pypi:
    needs: publish-to-testpypi
    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/p/cotainr

    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
    - uses: actions/checkout@v4  # Checkout because `uv publish` requires pyproject.toml
    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        name: dist
        path: dist
    - name: Set up uv
      uses: astral-sh/setup-uv@v5
    # - name: Publish distribution to PyPI
    #   run: uv publish

    # - name: Test PyPI build
    #   run: |
    #     uv pip install cotainr[tests]
    #     pytest .
