name: Scheduled documentation link check
on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '15 2 * * TUE'  # every Tuesday night
  workflow_dispatch:  # allow for manually trigging the workflow
jobs:
  check-docs-links:
    name: Check for broken links in documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: pip
      - name: Install docs dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -e .[docs]
      - name: Build documentation
        run: |
          make -C doc apidoc
          make -C doc relnotes
          make -C doc html
      - name: Run Sphinx linkcheck on documentation
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make -C doc linkcheck
