name: Scheduled documentation link check
on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '15 2 * * TUE'  # every Tuesday night
  workflow_dispatch:  # allow for manually trigging the workflow
jobs:
  check-docs-links:
    name: Check for broken links in documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up uv
        uses: astral-sh/setup-uv@v5

      - name: Install test dependencies
        run: |
          uv sync --python 3.12 --managed-python --group=docs --frozen
      - name: Build documentation
        run: |
          uv run make -C doc apidoc
          uv run make -C doc relnotes
          uv run make -C doc html
      - name: Run Sphinx linkcheck on documentation
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: uv run make -C doc linkcheck
